trigger:
  branches: 
    include:
    - master
  paths:
    include:
    - projectlist.txt

resources:
  repositories:
  - repository: PipelineTemplates
    type: github
    name: spanishwarship/azure-pipelines
    endpoint: 'spanishwarship'
  
jobs:
  - job: 'Read file'
  steps:
  - script: |
    cat projectlist.txt
    displayName: 'reading'
