trigger:
  branches: 
    include:
    - main
    - refs/tags/*

variables:
- name: tagname
  value: $Build.SourceBranch

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script: |
    echo "This is the tagname: $tagname"
    echo "this is the source branch: $Build.SourceBranch"
    echo "This is the source branch: $BUILD_SOURCEBRANCH"
    cat projectlist.txt
  displayName: 'reading'
