trigger:
  branches: 
    include:
    - master
  paths:
    include:
    - projectlist.txt

pool:
  vmImage: 'ubuntu-latest'
  
jobs:
  - job: 'Read file'
  steps:
  - script: |
      cat projectlist.txt
    displayName: 'reading'
