trigger:
  branches: 
    include:
    - master
  paths:
    include:
    - projectlist.txt

variables:
- name: tagname
  value: $Build.SourceBranch

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script: |
    echo $tagname
    cat projectlist.txt
  displayName: 'reading'
