trigger:
  branches: 
    include:
    - main
  paths:
    include:
    - projectlist.txt

variables:
- name: tagname
  value: $Build.SourceBranch

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script: |
    echo "This is the tagname: $tagname"
    echo "this is the source branch: $Build.SourceBranch"
    cat projectlist.txt
  displayName: 'reading'
